# Generated by Django 4.0.3 on 2022-09-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('status', models.IntegerField(choices=[(0, '未开始'), (1, '进行中'), (2, '已完成')], default=0, verbose_name='任务状态')),
                ('level', models.IntegerField(choices=[(0, '日常'), (1, '周常'), (2, '月常'), (3, '季常')], default=0, verbose_name='任务等级')),
                ('remark', models.CharField(max_length=50, verbose_name='任务备注')),
                ('description', models.CharField(max_length=50, verbose_name='任务描述')),
                ('award', models.CharField(max_length=50, verbose_name='任务奖励')),
            ],
            options={
                'verbose_name': '任务',
                'verbose_name_plural': '任务',
            },
        ),
    ]
